// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BroadcastRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBroadcastRepository is a mock of BroadcastRepository interface.
type MockBroadcastRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastRepositoryMockRecorder
}

// MockBroadcastRepositoryMockRecorder is the mock recorder for MockBroadcastRepository.
type MockBroadcastRepositoryMockRecorder struct {
	mock *MockBroadcastRepository
}

// NewMockBroadcastRepository creates a new mock instance.
func NewMockBroadcastRepository(ctrl *gomock.Controller) *MockBroadcastRepository {
	mock := &MockBroadcastRepository{ctrl: ctrl}
	mock.recorder = &MockBroadcastRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastRepository) EXPECT() *MockBroadcastRepositoryMockRecorder {
	return m.recorder
}

// CreateBroadcast mocks base method.
func (m *MockBroadcastRepository) CreateBroadcast(arg0 context.Context, arg1 *domain.Broadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBroadcast", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBroadcast indicates an expected call of CreateBroadcast.
func (mr *MockBroadcastRepositoryMockRecorder) CreateBroadcast(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBroadcast", reflect.TypeOf((*MockBroadcastRepository)(nil).CreateBroadcast), arg0, arg1)
}

// GetBroadcast mocks base method.
func (m *MockBroadcastRepository) GetBroadcast(arg0 context.Context, arg1, arg2 string) (*domain.Broadcast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Broadcast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBroadcast indicates an expected call of GetBroadcast.
func (mr *MockBroadcastRepositoryMockRecorder) GetBroadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcast", reflect.TypeOf((*MockBroadcastRepository)(nil).GetBroadcast), arg0, arg1, arg2)
}

// ListBroadcasts mocks base method.
func (m *MockBroadcastRepository) ListBroadcasts(arg0 context.Context, arg1 domain.ListBroadcastsParams) (*domain.BroadcastListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBroadcasts", arg0, arg1)
	ret0, _ := ret[0].(*domain.BroadcastListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBroadcasts indicates an expected call of ListBroadcasts.
func (mr *MockBroadcastRepositoryMockRecorder) ListBroadcasts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBroadcasts", reflect.TypeOf((*MockBroadcastRepository)(nil).ListBroadcasts), arg0, arg1)
}

// UpdateBroadcast mocks base method.
func (m *MockBroadcastRepository) UpdateBroadcast(arg0 context.Context, arg1 *domain.Broadcast) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBroadcast", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBroadcast indicates an expected call of UpdateBroadcast.
func (mr *MockBroadcastRepositoryMockRecorder) UpdateBroadcast(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBroadcast", reflect.TypeOf((*MockBroadcastRepository)(nil).UpdateBroadcast), arg0, arg1)
}
