// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: EmailQueueRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailQueueRepository is a mock of EmailQueueRepository interface.
type MockEmailQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailQueueRepositoryMockRecorder
}

// MockEmailQueueRepositoryMockRecorder is the mock recorder for MockEmailQueueRepository.
type MockEmailQueueRepositoryMockRecorder struct {
	mock *MockEmailQueueRepository
}

// NewMockEmailQueueRepository creates a new mock instance.
func NewMockEmailQueueRepository(ctrl *gomock.Controller) *MockEmailQueueRepository {
	mock := &MockEmailQueueRepository{ctrl: ctrl}
	mock.recorder = &MockEmailQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailQueueRepository) EXPECT() *MockEmailQueueRepositoryMockRecorder {
	return m.recorder
}

// CleanupDeadLetter mocks base method.
func (m *MockEmailQueueRepository) CleanupDeadLetter(arg0 context.Context, arg1 string, arg2 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupDeadLetter", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupDeadLetter indicates an expected call of CleanupDeadLetter.
func (mr *MockEmailQueueRepositoryMockRecorder) CleanupDeadLetter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDeadLetter", reflect.TypeOf((*MockEmailQueueRepository)(nil).CleanupDeadLetter), arg0, arg1, arg2)
}

// CleanupSent mocks base method.
func (m *MockEmailQueueRepository) CleanupSent(arg0 context.Context, arg1 string, arg2 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupSent", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupSent indicates an expected call of CleanupSent.
func (mr *MockEmailQueueRepositoryMockRecorder) CleanupSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupSent", reflect.TypeOf((*MockEmailQueueRepository)(nil).CleanupSent), arg0, arg1, arg2)
}

// CountBySourceAndStatus mocks base method.
func (m *MockEmailQueueRepository) CountBySourceAndStatus(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string, arg4 domain.EmailQueueStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySourceAndStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySourceAndStatus indicates an expected call of CountBySourceAndStatus.
func (mr *MockEmailQueueRepositoryMockRecorder) CountBySourceAndStatus(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySourceAndStatus", reflect.TypeOf((*MockEmailQueueRepository)(nil).CountBySourceAndStatus), arg0, arg1, arg2, arg3, arg4)
}

// Enqueue mocks base method.
func (m *MockEmailQueueRepository) Enqueue(arg0 context.Context, arg1 string, arg2 []*domain.EmailQueueEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockEmailQueueRepositoryMockRecorder) Enqueue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockEmailQueueRepository)(nil).Enqueue), arg0, arg1, arg2)
}

// EnqueueTx mocks base method.
func (m *MockEmailQueueRepository) EnqueueTx(arg0 context.Context, arg1 *sql.Tx, arg2 []*domain.EmailQueueEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTx indicates an expected call of EnqueueTx.
func (mr *MockEmailQueueRepositoryMockRecorder) EnqueueTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTx", reflect.TypeOf((*MockEmailQueueRepository)(nil).EnqueueTx), arg0, arg1, arg2)
}

// FetchPending mocks base method.
func (m *MockEmailQueueRepository) FetchPending(arg0 context.Context, arg1 string, arg2 int) ([]*domain.EmailQueueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPending", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.EmailQueueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPending indicates an expected call of FetchPending.
func (mr *MockEmailQueueRepositoryMockRecorder) FetchPending(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPending", reflect.TypeOf((*MockEmailQueueRepository)(nil).FetchPending), arg0, arg1, arg2)
}

// GetBySourceID mocks base method.
func (m *MockEmailQueueRepository) GetBySourceID(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string) ([]*domain.EmailQueueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySourceID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.EmailQueueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySourceID indicates an expected call of GetBySourceID.
func (mr *MockEmailQueueRepositoryMockRecorder) GetBySourceID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySourceID", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetBySourceID), arg0, arg1, arg2, arg3)
}

// GetDeadLetterEntries mocks base method.
func (m *MockEmailQueueRepository) GetDeadLetterEntries(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*domain.EmailQueueDeadLetter, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeadLetterEntries", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.EmailQueueDeadLetter)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeadLetterEntries indicates an expected call of GetDeadLetterEntries.
func (mr *MockEmailQueueRepositoryMockRecorder) GetDeadLetterEntries(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeadLetterEntries", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetDeadLetterEntries), arg0, arg1, arg2, arg3)
}

// GetStats mocks base method.
func (m *MockEmailQueueRepository) GetStats(arg0 context.Context, arg1 string) (*domain.EmailQueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0, arg1)
	ret0, _ := ret[0].(*domain.EmailQueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEmailQueueRepositoryMockRecorder) GetStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetStats), arg0, arg1)
}

// MarkAsFailed mocks base method.
func (m *MockEmailQueueRepository) MarkAsFailed(arg0 context.Context, arg1, arg2, arg3 string, arg4 *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsFailed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsFailed), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsProcessing mocks base method.
func (m *MockEmailQueueRepository) MarkAsProcessing(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessing", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessing indicates an expected call of MarkAsProcessing.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsProcessing(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessing", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsProcessing), arg0, arg1, arg2)
}

// MarkAsSent mocks base method.
func (m *MockEmailQueueRepository) MarkAsSent(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSent indicates an expected call of MarkAsSent.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSent", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsSent), arg0, arg1, arg2)
}

// MoveToDeadLetter mocks base method.
func (m *MockEmailQueueRepository) MoveToDeadLetter(arg0 context.Context, arg1 string, arg2 *domain.EmailQueueEntry, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDeadLetter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToDeadLetter indicates an expected call of MoveToDeadLetter.
func (mr *MockEmailQueueRepositoryMockRecorder) MoveToDeadLetter(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDeadLetter", reflect.TypeOf((*MockEmailQueueRepository)(nil).MoveToDeadLetter), arg0, arg1, arg2, arg3)
}

// RetryDeadLetter mocks base method.
func (m *MockEmailQueueRepository) RetryDeadLetter(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryDeadLetter", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryDeadLetter indicates an expected call of RetryDeadLetter.
func (mr *MockEmailQueueRepositoryMockRecorder) RetryDeadLetter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryDeadLetter", reflect.TypeOf((*MockEmailQueueRepository)(nil).RetryDeadLetter), arg0, arg1, arg2)
}
