// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: CustomEventService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockCustomEventService is a mock of CustomEventService interface.
type MockCustomEventService struct {
	ctrl     *gomock.Controller
	recorder *MockCustomEventServiceMockRecorder
}

// MockCustomEventServiceMockRecorder is the mock recorder for MockCustomEventService.
type MockCustomEventServiceMockRecorder struct {
	mock *MockCustomEventService
}

// NewMockCustomEventService creates a new mock instance.
func NewMockCustomEventService(ctrl *gomock.Controller) *MockCustomEventService {
	mock := &MockCustomEventService{ctrl: ctrl}
	mock.recorder = &MockCustomEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomEventService) EXPECT() *MockCustomEventServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockCustomEventService) CreateEvent(arg0 context.Context, arg1 *domain.CreateCustomEventRequest) (*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", arg0, arg1)
	ret0, _ := ret[0].(*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockCustomEventServiceMockRecorder) CreateEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockCustomEventService)(nil).CreateEvent), arg0, arg1)
}

// GetEvent mocks base method.
func (m *MockCustomEventService) GetEvent(arg0 context.Context, arg1, arg2, arg3 string) (*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockCustomEventServiceMockRecorder) GetEvent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockCustomEventService)(nil).GetEvent), arg0, arg1, arg2, arg3)
}

// ImportEvents mocks base method.
func (m *MockCustomEventService) ImportEvents(arg0 context.Context, arg1 *domain.ImportCustomEventsRequest) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportEvents", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportEvents indicates an expected call of ImportEvents.
func (mr *MockCustomEventServiceMockRecorder) ImportEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportEvents", reflect.TypeOf((*MockCustomEventService)(nil).ImportEvents), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockCustomEventService) ListEvents(arg0 context.Context, arg1 *domain.ListCustomEventsRequest) ([]*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].([]*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockCustomEventServiceMockRecorder) ListEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockCustomEventService)(nil).ListEvents), arg0, arg1)
}
