// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebhookEventRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookEventRepository is a mock of WebhookEventRepository interface.
type MockWebhookEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookEventRepositoryMockRecorder
}

// MockWebhookEventRepositoryMockRecorder is the mock recorder for MockWebhookEventRepository.
type MockWebhookEventRepositoryMockRecorder struct {
	mock *MockWebhookEventRepository
}

// NewMockWebhookEventRepository creates a new mock instance.
func NewMockWebhookEventRepository(ctrl *gomock.Controller) *MockWebhookEventRepository {
	mock := &MockWebhookEventRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookEventRepository) EXPECT() *MockWebhookEventRepositoryMockRecorder {
	return m.recorder
}

// GetEventByID mocks base method.
func (m *MockWebhookEventRepository) GetEventByID(arg0 context.Context, arg1 string) (*domain.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventByID), arg0, arg1)
}

// GetEventCount mocks base method.
func (m *MockWebhookEventRepository) GetEventCount(arg0 context.Context, arg1 string, arg2 domain.EmailEventType) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventCount", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventCount indicates an expected call of GetEventCount.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventCount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventCount", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventCount), arg0, arg1, arg2)
}

// GetEventsByBroadcastID mocks base method.
func (m *MockWebhookEventRepository) GetEventsByBroadcastID(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*domain.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByBroadcastID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByBroadcastID indicates an expected call of GetEventsByBroadcastID.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventsByBroadcastID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByBroadcastID", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventsByBroadcastID), arg0, arg1, arg2, arg3)
}

// GetEventsByMessageID mocks base method.
func (m *MockWebhookEventRepository) GetEventsByMessageID(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*domain.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByMessageID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByMessageID indicates an expected call of GetEventsByMessageID.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventsByMessageID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByMessageID", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventsByMessageID), arg0, arg1, arg2, arg3)
}

// GetEventsByTransactionalID mocks base method.
func (m *MockWebhookEventRepository) GetEventsByTransactionalID(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*domain.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByTransactionalID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByTransactionalID indicates an expected call of GetEventsByTransactionalID.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventsByTransactionalID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByTransactionalID", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventsByTransactionalID), arg0, arg1, arg2, arg3)
}

// GetEventsByType mocks base method.
func (m *MockWebhookEventRepository) GetEventsByType(arg0 context.Context, arg1 string, arg2 domain.EmailEventType, arg3, arg4 int) ([]*domain.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByType", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByType indicates an expected call of GetEventsByType.
func (mr *MockWebhookEventRepositoryMockRecorder) GetEventsByType(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByType", reflect.TypeOf((*MockWebhookEventRepository)(nil).GetEventsByType), arg0, arg1, arg2, arg3, arg4)
}

// StoreEvent mocks base method.
func (m *MockWebhookEventRepository) StoreEvent(arg0 context.Context, arg1 *domain.WebhookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreEvent indicates an expected call of StoreEvent.
func (mr *MockWebhookEventRepositoryMockRecorder) StoreEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEvent", reflect.TypeOf((*MockWebhookEventRepository)(nil).StoreEvent), arg0, arg1)
}
