// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: TransactionalNotificationService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTransactionalNotificationService is a mock of TransactionalNotificationService interface.
type MockTransactionalNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalNotificationServiceMockRecorder
}

// MockTransactionalNotificationServiceMockRecorder is the mock recorder for MockTransactionalNotificationService.
type MockTransactionalNotificationServiceMockRecorder struct {
	mock *MockTransactionalNotificationService
}

// NewMockTransactionalNotificationService creates a new mock instance.
func NewMockTransactionalNotificationService(ctrl *gomock.Controller) *MockTransactionalNotificationService {
	mock := &MockTransactionalNotificationService{ctrl: ctrl}
	mock.recorder = &MockTransactionalNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalNotificationService) EXPECT() *MockTransactionalNotificationServiceMockRecorder {
	return m.recorder
}

// CreateNotification mocks base method.
func (m *MockTransactionalNotificationService) CreateNotification(ctx context.Context, workspace string, params domain.TransactionalNotificationCreateParams) (*domain.TransactionalNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, workspace, params)
	ret0, _ := ret[0].(*domain.TransactionalNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockTransactionalNotificationServiceMockRecorder) CreateNotification(ctx, workspace, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockTransactionalNotificationService)(nil).CreateNotification), ctx, workspace, params)
}

// DeleteNotification mocks base method.
func (m *MockTransactionalNotificationService) DeleteNotification(ctx context.Context, workspace, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", ctx, workspace, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockTransactionalNotificationServiceMockRecorder) DeleteNotification(ctx, workspace, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockTransactionalNotificationService)(nil).DeleteNotification), ctx, workspace, id)
}

// GetNotification mocks base method.
func (m *MockTransactionalNotificationService) GetNotification(ctx context.Context, workspace, id string) (*domain.TransactionalNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", ctx, workspace, id)
	ret0, _ := ret[0].(*domain.TransactionalNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockTransactionalNotificationServiceMockRecorder) GetNotification(ctx, workspace, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockTransactionalNotificationService)(nil).GetNotification), ctx, workspace, id)
}

// ListNotifications mocks base method.
func (m *MockTransactionalNotificationService) ListNotifications(ctx context.Context, workspace string, filter map[string]interface{}, limit, offset int) ([]*domain.TransactionalNotification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, workspace, filter, limit, offset)
	ret0, _ := ret[0].([]*domain.TransactionalNotification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockTransactionalNotificationServiceMockRecorder) ListNotifications(ctx, workspace, filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockTransactionalNotificationService)(nil).ListNotifications), ctx, workspace, filter, limit, offset)
}

// SendNotification mocks base method.
func (m *MockTransactionalNotificationService) SendNotification(ctx context.Context, workspace string, params domain.TransactionalNotificationSendParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, workspace, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockTransactionalNotificationServiceMockRecorder) SendNotification(ctx, workspace, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockTransactionalNotificationService)(nil).SendNotification), ctx, workspace, params)
}

// UpdateNotification mocks base method.
func (m *MockTransactionalNotificationService) UpdateNotification(ctx context.Context, workspace, id string, params domain.TransactionalNotificationUpdateParams) (*domain.TransactionalNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotification", ctx, workspace, id, params)
	ret0, _ := ret[0].(*domain.TransactionalNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotification indicates an expected call of UpdateNotification.
func (mr *MockTransactionalNotificationServiceMockRecorder) UpdateNotification(ctx, workspace, id, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotification", reflect.TypeOf((*MockTransactionalNotificationService)(nil).UpdateNotification), ctx, workspace, id, params)
} 