// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: TaskRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CompleteSubtask mocks base method.
func (m *MockTaskRepository) CompleteSubtask(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSubtask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSubtask indicates an expected call of CompleteSubtask.
func (mr *MockTaskRepositoryMockRecorder) CompleteSubtask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSubtask", reflect.TypeOf((*MockTaskRepository)(nil).CompleteSubtask), arg0, arg1)
}

// CompleteSubtaskTx mocks base method.
func (m *MockTaskRepository) CompleteSubtaskTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSubtaskTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSubtaskTx indicates an expected call of CompleteSubtaskTx.
func (mr *MockTaskRepositoryMockRecorder) CompleteSubtaskTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSubtaskTx", reflect.TypeOf((*MockTaskRepository)(nil).CompleteSubtaskTx), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockTaskRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), arg0, arg1, arg2)
}

// CreateSubtasks mocks base method.
func (m *MockTaskRepository) CreateSubtasks(arg0 context.Context, arg1, arg2 string, arg3 int) ([]*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubtasks", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubtasks indicates an expected call of CreateSubtasks.
func (mr *MockTaskRepositoryMockRecorder) CreateSubtasks(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubtasks", reflect.TypeOf((*MockTaskRepository)(nil).CreateSubtasks), arg0, arg1, arg2, arg3)
}

// CreateSubtasksTx mocks base method.
func (m *MockTaskRepository) CreateSubtasksTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 int) ([]*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubtasksTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubtasksTx indicates an expected call of CreateSubtasksTx.
func (mr *MockTaskRepositoryMockRecorder) CreateSubtasksTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubtasksTx", reflect.TypeOf((*MockTaskRepository)(nil).CreateSubtasksTx), arg0, arg1, arg2, arg3, arg4)
}

// CreateTx mocks base method.
func (m *MockTaskRepository) CreateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockTaskRepositoryMockRecorder) CreateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockTaskRepository)(nil).CreateTx), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockTaskRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepository)(nil).Delete), arg0, arg1, arg2)
}

// FailSubtask mocks base method.
func (m *MockTaskRepository) FailSubtask(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailSubtask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailSubtask indicates an expected call of FailSubtask.
func (mr *MockTaskRepositoryMockRecorder) FailSubtask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailSubtask", reflect.TypeOf((*MockTaskRepository)(nil).FailSubtask), arg0, arg1, arg2)
}

// FailSubtaskTx mocks base method.
func (m *MockTaskRepository) FailSubtaskTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailSubtaskTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailSubtaskTx indicates an expected call of FailSubtaskTx.
func (mr *MockTaskRepositoryMockRecorder) FailSubtaskTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailSubtaskTx", reflect.TypeOf((*MockTaskRepository)(nil).FailSubtaskTx), arg0, arg1, arg2, arg3)
}

// Get mocks base method.
func (m *MockTaskRepository) Get(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskRepositoryMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskRepository)(nil).Get), arg0, arg1, arg2)
}

// GetNextBatch mocks base method.
func (m *MockTaskRepository) GetNextBatch(arg0 context.Context, arg1 int) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextBatch", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextBatch indicates an expected call of GetNextBatch.
func (mr *MockTaskRepositoryMockRecorder) GetNextBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextBatch", reflect.TypeOf((*MockTaskRepository)(nil).GetNextBatch), arg0, arg1)
}

// GetSubtask mocks base method.
func (m *MockTaskRepository) GetSubtask(arg0 context.Context, arg1 string) (*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubtask", arg0, arg1)
	ret0, _ := ret[0].(*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubtask indicates an expected call of GetSubtask.
func (mr *MockTaskRepositoryMockRecorder) GetSubtask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubtask", reflect.TypeOf((*MockTaskRepository)(nil).GetSubtask), arg0, arg1)
}

// GetSubtaskTx mocks base method.
func (m *MockTaskRepository) GetSubtaskTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubtaskTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubtaskTx indicates an expected call of GetSubtaskTx.
func (mr *MockTaskRepositoryMockRecorder) GetSubtaskTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubtaskTx", reflect.TypeOf((*MockTaskRepository)(nil).GetSubtaskTx), arg0, arg1, arg2)
}

// GetSubtasks mocks base method.
func (m *MockTaskRepository) GetSubtasks(arg0 context.Context, arg1 string) ([]*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubtasks", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubtasks indicates an expected call of GetSubtasks.
func (mr *MockTaskRepositoryMockRecorder) GetSubtasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubtasks", reflect.TypeOf((*MockTaskRepository)(nil).GetSubtasks), arg0, arg1)
}

// GetSubtasksTx mocks base method.
func (m *MockTaskRepository) GetSubtasksTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) ([]*domain.Subtask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubtasksTx", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Subtask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubtasksTx indicates an expected call of GetSubtasksTx.
func (mr *MockTaskRepositoryMockRecorder) GetSubtasksTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubtasksTx", reflect.TypeOf((*MockTaskRepository)(nil).GetSubtasksTx), arg0, arg1, arg2)
}

// GetTaskByBroadcastID mocks base method.
func (m *MockTaskRepository) GetTaskByBroadcastID(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByBroadcastID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByBroadcastID indicates an expected call of GetTaskByBroadcastID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByBroadcastID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByBroadcastID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByBroadcastID), arg0, arg1, arg2)
}

// GetTaskByBroadcastIDTx mocks base method.
func (m *MockTaskRepository) GetTaskByBroadcastIDTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByBroadcastIDTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByBroadcastIDTx indicates an expected call of GetTaskByBroadcastIDTx.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByBroadcastIDTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByBroadcastIDTx", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByBroadcastIDTx), arg0, arg1, arg2, arg3)
}

// GetTx mocks base method.
func (m *MockTaskRepository) GetTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTx indicates an expected call of GetTx.
func (mr *MockTaskRepositoryMockRecorder) GetTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTx", reflect.TypeOf((*MockTaskRepository)(nil).GetTx), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockTaskRepository) List(arg0 context.Context, arg1 string, arg2 domain.TaskFilter) ([]*domain.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), arg0, arg1, arg2)
}

// MarkAsCompleted mocks base method.
func (m *MockTaskRepository) MarkAsCompleted(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompleted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsCompleted indicates an expected call of MarkAsCompleted.
func (mr *MockTaskRepositoryMockRecorder) MarkAsCompleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompleted", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsCompleted), arg0, arg1, arg2)
}

// MarkAsCompletedTx mocks base method.
func (m *MockTaskRepository) MarkAsCompletedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompletedTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsCompletedTx indicates an expected call of MarkAsCompletedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsCompletedTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompletedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsCompletedTx), arg0, arg1, arg2, arg3)
}

// MarkAsFailed mocks base method.
func (m *MockTaskRepository) MarkAsFailed(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockTaskRepositoryMockRecorder) MarkAsFailed(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsFailed), arg0, arg1, arg2, arg3)
}

// MarkAsFailedTx mocks base method.
func (m *MockTaskRepository) MarkAsFailedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailedTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailedTx indicates an expected call of MarkAsFailedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsFailedTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsFailedTx), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsPaused mocks base method.
func (m *MockTaskRepository) MarkAsPaused(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPaused", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPaused indicates an expected call of MarkAsPaused.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPaused(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPaused", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPaused), arg0, arg1, arg2, arg3)
}

// MarkAsPausedTx mocks base method.
func (m *MockTaskRepository) MarkAsPausedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPausedTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPausedTx indicates an expected call of MarkAsPausedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPausedTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPausedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPausedTx), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsRunning mocks base method.
func (m *MockTaskRepository) MarkAsRunning(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRunning", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRunning indicates an expected call of MarkAsRunning.
func (mr *MockTaskRepositoryMockRecorder) MarkAsRunning(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRunning", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsRunning), arg0, arg1, arg2, arg3)
}

// MarkAsRunningTx mocks base method.
func (m *MockTaskRepository) MarkAsRunningTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRunningTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRunningTx indicates an expected call of MarkAsRunningTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsRunningTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRunningTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsRunningTx), arg0, arg1, arg2, arg3, arg4)
}

// SaveState mocks base method.
func (m *MockTaskRepository) SaveState(arg0 context.Context, arg1, arg2 string, arg3 float64, arg4 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockTaskRepositoryMockRecorder) SaveState(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockTaskRepository)(nil).SaveState), arg0, arg1, arg2, arg3, arg4)
}

// SaveStateTx mocks base method.
func (m *MockTaskRepository) SaveStateTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 float64, arg5 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStateTx", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStateTx indicates an expected call of SaveStateTx.
func (mr *MockTaskRepositoryMockRecorder) SaveStateTx(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStateTx", reflect.TypeOf((*MockTaskRepository)(nil).SaveStateTx), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Update mocks base method.
func (m *MockTaskRepository) Update(arg0 context.Context, arg1 string, arg2 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepository)(nil).Update), arg0, arg1, arg2)
}

// UpdateSubtaskProgress mocks base method.
func (m *MockTaskRepository) UpdateSubtaskProgress(arg0 context.Context, arg1 string, arg2 float64, arg3 domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubtaskProgress", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubtaskProgress indicates an expected call of UpdateSubtaskProgress.
func (mr *MockTaskRepositoryMockRecorder) UpdateSubtaskProgress(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubtaskProgress", reflect.TypeOf((*MockTaskRepository)(nil).UpdateSubtaskProgress), arg0, arg1, arg2, arg3)
}

// UpdateSubtaskProgressTx mocks base method.
func (m *MockTaskRepository) UpdateSubtaskProgressTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 float64, arg4 domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubtaskProgressTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubtaskProgressTx indicates an expected call of UpdateSubtaskProgressTx.
func (mr *MockTaskRepositoryMockRecorder) UpdateSubtaskProgressTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubtaskProgressTx", reflect.TypeOf((*MockTaskRepository)(nil).UpdateSubtaskProgressTx), arg0, arg1, arg2, arg3, arg4)
}

// UpdateTaskProgressFromSubtasks mocks base method.
func (m *MockTaskRepository) UpdateTaskProgressFromSubtasks(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskProgressFromSubtasks", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskProgressFromSubtasks indicates an expected call of UpdateTaskProgressFromSubtasks.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskProgressFromSubtasks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskProgressFromSubtasks", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskProgressFromSubtasks), arg0, arg1, arg2)
}

// UpdateTaskProgressFromSubtasksTx mocks base method.
func (m *MockTaskRepository) UpdateTaskProgressFromSubtasksTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskProgressFromSubtasksTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskProgressFromSubtasksTx indicates an expected call of UpdateTaskProgressFromSubtasksTx.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskProgressFromSubtasksTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskProgressFromSubtasksTx", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskProgressFromSubtasksTx), arg0, arg1, arg2, arg3)
}

// UpdateTx mocks base method.
func (m *MockTaskRepository) UpdateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockTaskRepositoryMockRecorder) UpdateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTx), arg0, arg1, arg2, arg3)
}

// WithTransaction mocks base method.
func (m *MockTaskRepository) WithTransaction(arg0 context.Context, arg1 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTaskRepositoryMockRecorder) WithTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTaskRepository)(nil).WithTransaction), arg0, arg1)
}
