// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	paseto "aidanwoods.dev/go-paseto"
	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)


// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// AuthenticateUserForWorkspace mocks base method.
func (m *MockAuthService) AuthenticateUserForWorkspace(ctx context.Context, workspaceID string) (context.Context, *domain.User, *domain.UserWorkspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUserForWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*domain.User)
	ret2, _ := ret[2].(*domain.UserWorkspace)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// AuthenticateUserForWorkspace indicates an expected call of AuthenticateUserForWorkspace.
func (mr *MockAuthServiceMockRecorder) AuthenticateUserForWorkspace(ctx, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUserForWorkspace", reflect.TypeOf((*MockAuthService)(nil).AuthenticateUserForWorkspace), ctx, workspaceID)
}

// AuthenticateUserFromContext mocks base method.
func (m *MockAuthService) AuthenticateUserFromContext(ctx context.Context) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUserFromContext", ctx)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUserFromContext indicates an expected call of AuthenticateUserFromContext.
func (mr *MockAuthServiceMockRecorder) AuthenticateUserFromContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUserFromContext", reflect.TypeOf((*MockAuthService)(nil).AuthenticateUserFromContext), ctx)
}

// GenerateAPIAuthToken mocks base method.
func (m *MockAuthService) GenerateAPIAuthToken(user *domain.User) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAPIAuthToken", user)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateAPIAuthToken indicates an expected call of GenerateAPIAuthToken.
func (mr *MockAuthServiceMockRecorder) GenerateAPIAuthToken(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAPIAuthToken", reflect.TypeOf((*MockAuthService)(nil).GenerateAPIAuthToken), user)
}

// GenerateInvitationToken mocks base method.
func (m *MockAuthService) GenerateInvitationToken(invitation *domain.WorkspaceInvitation) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvitationToken", invitation)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateInvitationToken indicates an expected call of GenerateInvitationToken.
func (mr *MockAuthServiceMockRecorder) GenerateInvitationToken(invitation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvitationToken", reflect.TypeOf((*MockAuthService)(nil).GenerateInvitationToken), invitation)
}

// GenerateUserAuthToken mocks base method.
func (m *MockAuthService) GenerateUserAuthToken(user *domain.User, sessionID string, expiresAt time.Time) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUserAuthToken", user, sessionID, expiresAt)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateUserAuthToken indicates an expected call of GenerateUserAuthToken.
func (mr *MockAuthServiceMockRecorder) GenerateUserAuthToken(user, sessionID, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUserAuthToken", reflect.TypeOf((*MockAuthService)(nil).GenerateUserAuthToken), user, sessionID, expiresAt)
}

// GetPrivateKey mocks base method.
func (m *MockAuthService) GetPrivateKey() (paseto.V4AsymmetricSecretKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKey")
	ret0, _ := ret[0].(paseto.V4AsymmetricSecretKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateKey indicates an expected call of GetPrivateKey.
func (mr *MockAuthServiceMockRecorder) GetPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKey", reflect.TypeOf((*MockAuthService)(nil).GetPrivateKey))
}

// GetPublicKey mocks base method.
func (m *MockAuthService) GetPublicKey() (paseto.V4AsymmetricPublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey")
	ret0, _ := ret[0].(paseto.V4AsymmetricPublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockAuthServiceMockRecorder) GetPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockAuthService)(nil).GetPublicKey))
}

// InvalidateKeyCache mocks base method.
func (m *MockAuthService) InvalidateKeyCache() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateKeyCache")
}

// InvalidateKeyCache indicates an expected call of InvalidateKeyCache.
func (mr *MockAuthServiceMockRecorder) InvalidateKeyCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateKeyCache", reflect.TypeOf((*MockAuthService)(nil).InvalidateKeyCache))
}

// ValidateInvitationToken mocks base method.
func (m *MockAuthService) ValidateInvitationToken(token string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInvitationToken", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ValidateInvitationToken indicates an expected call of ValidateInvitationToken.
func (mr *MockAuthServiceMockRecorder) ValidateInvitationToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInvitationToken", reflect.TypeOf((*MockAuthService)(nil).ValidateInvitationToken), token)
}

// VerifyUserSession mocks base method.
func (m *MockAuthService) VerifyUserSession(ctx context.Context, userID, sessionID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserSession indicates an expected call of VerifyUserSession.
func (mr *MockAuthServiceMockRecorder) VerifyUserSession(ctx, userID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserSession", reflect.TypeOf((*MockAuthService)(nil).VerifyUserSession), ctx, userID, sessionID)
}
