// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/service/broadcast (interfaces: BroadcastOrchestratorInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBroadcastOrchestratorInterface is a mock of BroadcastOrchestratorInterface interface.
type MockBroadcastOrchestratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastOrchestratorInterfaceMockRecorder
}

// MockBroadcastOrchestratorInterfaceMockRecorder is the mock recorder for MockBroadcastOrchestratorInterface.
type MockBroadcastOrchestratorInterfaceMockRecorder struct {
	mock *MockBroadcastOrchestratorInterface
}

// NewMockBroadcastOrchestratorInterface creates a new mock instance.
func NewMockBroadcastOrchestratorInterface(ctrl *gomock.Controller) *MockBroadcastOrchestratorInterface {
	mock := &MockBroadcastOrchestratorInterface{ctrl: ctrl}
	mock.recorder = &MockBroadcastOrchestratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastOrchestratorInterface) EXPECT() *MockBroadcastOrchestratorInterfaceMockRecorder {
	return m.recorder
}

// CanProcess mocks base method.
func (m *MockBroadcastOrchestratorInterface) CanProcess(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProcess", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanProcess indicates an expected call of CanProcess.
func (mr *MockBroadcastOrchestratorInterfaceMockRecorder) CanProcess(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProcess", reflect.TypeOf((*MockBroadcastOrchestratorInterface)(nil).CanProcess), arg0)
}

// Process mocks base method.
func (m *MockBroadcastOrchestratorInterface) Process(arg0 context.Context, arg1 *domain.Task) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockBroadcastOrchestratorInterfaceMockRecorder) Process(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockBroadcastOrchestratorInterface)(nil).Process), arg0, arg1)
}
